### ISSUE TITLE
establish a common tag/topic?

### ISSUE THREAD

**Issue by splitbrain** [reHackable/other-repos#1]
Github allows tagging projects with topics. It would be useful if we could establish a standard topic for all reMarkable related projects to differentiate them from the remarkable Markdown editor. Maybe `remarkable-paper` or `remarkable-tablet`? Would be a good start to tag all projects within this organisation accordingly.

Once this is established, maintaining the list in this repository should become somewhat easier.

**Comment by Ameb** [comment]
Didn't know about that! [Here](https://help.github.com/articles/about-topics/) Is more info.
 We would need to ask everyone to use the topic. And yeah, it would allow us to automate the list (or the list will not even be needed).
Thank you

**Comment by morngrar** [comment]
This sounded like such a good idea that I wanted to pitch in! 

I like `remarkable-tablet` best

**Comment by CTXz** [comment]
`remarkable-tablet` it is
Thanks for raising our awareness!

**Issue closed**

**Comment by Ameb** [comment]
Just adding a template for further requests
```
Add the `remarkable-tablet` topic to the repo
```

```
In an effort to make projects for the reMarkable tablet easier to find on GitHub, a common topic named `remarkable-tablet` has been established (See [reHackable/awesome-reMarkable#1](https://github.com/reHackable/awesome-reMarkable/issues/1)).

It would be awesome if you could tag this project with the `remarkable-tablet` topic.
 
 There's more info on [Classifying your repository with topics](https://help.github.com/articles/classifying-your-repository-with-topics/) available in the GitHub help.
 
 A list of already tagged projects can be found here: [Projects in Topic remarkable-tablet](https://github.com/topics/remarkable-tablet).
```
