### ISSUE TITLE
Rename to something with awesome list

### ISSUE THREAD

**Issue by danr** [reHackable/other-repos#4]
Instead of _other-repos_ we could call this repo a curated list of awesome reMarkable software.

See: https://github.com/sindresorhus/awesome

**Comment by CTXz** [comment]
I propose **_reLatable_** =D

**Comment by Ameb** [comment]
maybe `awesome` its enough. Would be `reHackable/awesome` after all. I do not like `reLatable` because of too much `re-`

**Comment by CTXz** [comment]
Awesome it is.... (no really, it's awesome)

But... how about giving **_reAwesome_** a try?
Just kidding :smile: 

Issue closed!
